version: '3.4'

services:
  devfreela.db:
    container_name: devfreeladb
    hostname: devfreeladb
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: D3vfrelaa.@

networks:
  default:
    name: service_devfreela